apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP  # Need not specify it automatically takes
  ports: 
  - targetPort: 80
    port: 80
  selector:
      app: myapp
      type: back-end