apiVersion: apps/v1
kind: Deployment
metadata: #For the Deployment
  name: demo
  labels:
    app: mydemo
    type: frontend
spec:
  template:
    metadata: #For the Pod
      name: nginx
      labels:
        app: myapp
        type: frontend
    spec:
      containers: #Array
        - name: demo
          image: nginx:alpine 
  replicas: 3
  selector:
    matchLabels:
      app: myapp